# This workflow will build the Vue app into the /docs folder
on:
  push:
    branches: [master]

env:
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install and build
      run: |
        npm install
        npm run build
    - name: publish latest version to docs
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add -A docs
        git commit -m "publish latest app version"
        git push
    - name: Commit latest app to server repository
      if: always()
      run: |
        git clone git://github.com/music-assistant/server.git /tmp/mass-server
        cp -R docs /tmp/mass-server/music_assistant/
        cd /tmp/mass-server/
        mv music_assistant/docs music_assistant/web
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add -A music_assistant/web
        git commit -m "publish latest app version"
        git push "https://marcelveldt:${{ secrets.GITHUB_TOKEN }}@github.com/music-assistant/server.git"
    # - name: Push latest app to server repository
    #   uses: ad-m/github-push-action@master
    #   if: always()
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     repository: git://github.com/music-assistant/server.git
    #     directory: /tmp/mass-server
  
  
