# This workflow will build the Vue app into the /docs folder
on:
  push:
    branches: [master]

env:
  NODE_VERSION: '14.9'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install and build
      run: |
        npm install
        npm run build
    - name: publish latest version to docs
      # note: will fail if there is no new version
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add -A docs
        git commit -m "publish latest app version"
        git push -f
  
